name: Deploy to Debian Server

on:
  push:
    branches:
      - main # Solo se ejecuta cuando hay cambios en la rama main

jobs:
  deploy:
    runs-on: self-hosted # Ejecuta los comandos directamente en tu laptop
    
    steps:
    - name: Descargar cambios y reiniciar el bot
      run: |
        if [ -d "$HOME/Github/Scrobbly" ]; then cd "$HOME/Github/Scrobbly"; elif [ -d "$HOME/Scrobbly" ]; then cd "$HOME/Scrobbly"; fi
        git fetch origin main
        git reset --hard origin/main
        if [ -f ".venv/bin/activate" ]; then source .venv/bin/activate; elif [ -f "venv/bin/activate" ]; then source venv/bin/activate; fi
        pip install -r requirements.txt
        pm2 restart scrobbly

